### ISSUE TITLE
Download script reports success but does not create files

### ISSUE THREAD

**Issue by Ghirigoro** [JetBrains/youtrack-scripting#9]
I've set up an environment and am able to connect to the server and list and upload workflows. Downloading reports success (i.e. it prints `File extracted into '/Users/me/Desktop/'`) but no actual files are created and no error is reported.

P.S. - I've tried using both `yarn` and `npm` with identical results.

OS: MacOS 10.15.6
Model: Macbook Pro 16, 2019

**Comment by prowebcraft** [comment]
Hello, same result with the latest version (0.0.24). 
Previous version (0.0.24) works fine for me last year, but now it's also broken with exception:

`fs.js:39
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:39:5
    at req_ (E:\htdocs\youtrack-workflows\node_modules\natives\index.js:143:24)
    at Object.req [as require] (E:\htdocs\youtrack-workflows\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (E:\htdocs\youtrack-workflows\node_modules\fstream\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)`

**Comment by maksimr** [comment]
@Ghirigoro does  the problem still exists? Also, could you provide version of `node`, `npm` and `youtrack-scripting`

Thanks

**Comment by Ghirigoro** [comment]
@maksimr Sorry, I gave up on YouTrack scripting a few months ago and am unsure what versions I was using at the time, or whether the error is still occurring.

**Comment by maksimr** [comment]
@Ghirigoro ok, thanks.

@prowebcraft Do you still have your problem?

**Comment by prowebcraft** [comment]
@maksimr, yep.

node 14.4.0
npm 6.14.5
youtrack-scripting 0.0.24

**Comment by maksimr** [comment]
@prowebcraft Am I right that you use Windows? Could you check how does it work in "Power shall" because I can't reproduce it on Windows 8 Pro with the latest stable version  of node@14.15.4 (includes npm 6.14.10)
Thanks

![image](https://user-images.githubusercontent.com/616193/106458590-ae32a900-64a1-11eb-91b8-4d94519a7b31.png)

**Comment by prowebcraft** [comment]
@maksimr, Win 10 Home, PS 5.1.19041.610 - same result. 
![image](https://user-images.githubusercontent.com/4133348/106460498-7da03e80-64a4-11eb-97fc-93da74e002f4.png)
